server:
  port: 8501

# give a name to account service app to display name on the eureka server
spring:
  application:
    name: account-service
  zipkin: # give path to account service to register zipkin server
    base-url: http://localhost:9411/

  # admin server config to see detail of application details
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

# to register account service to eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ms:
  cassandra:
    contact:
      point: 127.0.0.1
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra