server:
  port: 8761

# give a name to eureka server
spring:
  application:
    name: eureka-service
  zipkin: # give path to eureka service to register zipkin server
    base-url: http://localhost:9411/
