server:
  port: 8503

# give a name to notification service app to display name on the eureka server
spring:
  application:
    name: notification-service
  rabbitmq:
    username: muhammedtopgul
    password: muhammedtopgul
  cloud:
    stream:
      bindings:
        input: # this will read so, input in ticket-service.yml will write so it has output
          destination: msqueue
  zipkin: # give path to notification service to register zipkin server
    base-url: http://localhost:9411/

  # admin server config to see detail of application details
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

# to register notification service to eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
