server:
  port: 8502

# give a name to account service app to display name on the eureka server
spring:
  application:
    name: ticket-service
  # mysql config
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    hibernate:
      ddl-auto: update

# to register account service to eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
